% unit       : celex:32024R1689/oj#art_19
% context    : CHAPTER III HIGH-RISK AI SYSTEMS > SECTION 3 Obligations of providers and deployers of high-risk AI systems and other parties
% slice sha  : 0f2572a54d8a70004ffa8312da33d5b9f2fee58cc54f96ca38f1086fe949fd51
% model      : gpt-oss:120b-cloud
% signature  : 58e38705e9c73a9544b26bad9a5800681f39e7ee543b83f5b600690c8280f095
% call key   : c921714faf8746bfdc6861694bd2d826d45c0d96c71ec28f6b1c65b5e4d228b5
% cached     : False
% title      : Automatically generated logs
:- pred logs_under_control/2, gloss('logs of a high‑risk AI system are under the control of the provider'), source('celex:32024R1689/oj#art_19').
:- pred automatically_generated_by/1, gloss('logs are automatically generated by the high‑risk AI system'), source('celex:32024R1689/oj#art_19').
:- pred financial_institution/1, gloss('provider is a financial institution subject to Union financial services law'), source('celex:32024R1689/oj#art_19').
:- pred documentation_under_financial_services_law/1, gloss('documentation kept under the relevant financial services law'), source('celex:32024R1689/oj#art_19').

must_keep(Provider, logs(HighRiskAI, period(months(6)))) :-
    provider(Provider),
    high_risk_ai_system(HighRiskAI),
    logs_under_control(Provider, HighRiskAI),
    automatically_generated_by(HighRiskAI).

must_maintain(Provider, logs(HighRiskAI)) :-
    provider(Provider),
    financial_institution(Provider),
    high_risk_ai_system(HighRiskAI),
    automatically_generated_by(HighRiskAI),
    documentation_under_financial_services_law(Provider).

provenance(must_keep/2, 'celex:32024R1689/oj#art_19').
provenance(must_maintain/2, 'celex:32024R1689/oj#art_19').

references('celex:32024R1689/oj#art_19', 'celex:32024R1689/oj#art_12/par_1').
