% ============================================================
% FROZEN SIGNATURE -- the predicate vocabulary for this program.
%
% Generated by ONE LLM call over the definitions article, then frozen.
% Every Phase B rule-generation call receives this file verbatim, so all
% Phase B calls are mutually independent and order-free.
%
% source slice : art_3 (68 items)
% slice sha256 : bd070405dcb2476388bc2d0b6018a548509e95293c8e275ca8cfa8674b817792
% source unit  : celex:32024R1689/oj#art_3
% model        : gpt-oss:120b-cloud (temperature 0.0, seed 0)
% definitions  : Article 3
% prompt sha   : f33cc80bf5b4055799c4ff6c608ad2bc96cccac5b3af006fd87030f9091301d9
% declarations : 72
%
% DO NOT EDIT BY HAND without re-running Phase B: rules generated against a
% different signature may reference predicates that no longer exist.
% ============================================================

:- pred ai_system/1, gloss('machine‑based system with autonomy'), source('1').
:- pred risk/1, gloss('probability and severity of harm'), source('2').
:- pred provider/1, gloss('entity that develops or places an AI system'), source('3').
:- pred deployer/1, gloss('entity using an AI system under its authority'), source('4').
:- pred authorised_representative/1, gloss('person in the Union mandated by a provider'), source('5').
:- pred importer/1, gloss('entity placing an AI system on the market in the Union'), source('6').
:- pred distributor/1, gloss('entity in the supply chain other than provider or importer'), source('7').
:- pred operator/1, gloss('provider, product manufacturer, deployer, authorised representative, importer or distributor'), source('8').
:- pred placing_on_market/1, gloss('first making available of an AI system on the Union market'), source('9').
:- pred making_available_on_market/1, gloss('supply of an AI system for distribution or use on the Union market'), source('10').
:- pred putting_into_service/1, gloss('supply of an AI system for first use by the deployer'), source('11').
:- pred intended_purpose/1, gloss('use for which an AI system is intended by the provider'), source('12').
:- pred reasonably_foreseeable_misuse/1, gloss('use not in accordance with intended purpose but foreseeable'), source('13').
:- pred safety_component/1, gloss('component fulfilling a safety function'), source('14').
:- pred instructions_for_use/1, gloss('information provided by the provider to the deployer'), source('15').
:- pred recall_of_ai_system/1, gloss('measure to return or disable an AI system'), source('16').
:- pred withdrawal_of_ai_system/1, gloss('measure to prevent AI system being made available'), source('17').
:- pred performance_of_ai_system/1, gloss('ability of an AI system to achieve its intended purpose'), source('18').
:- pred notifying_authority/1, gloss('national authority for conformity assessment procedures'), source('19').
:- pred conformity_assessment/1, gloss('process to demonstrate requirements are fulfilled'), source('20').
:- pred conformity_assessment_body/1, gloss('body performing third‑party conformity assessment'), source('21').
:- pred notified_body/1, gloss('conformity assessment body notified in accordance with the regulation'), source('22').
:- pred substantial_modification/1, gloss('change to an AI system after market placement affecting compliance'), source('23').
:- pred ce_marking/1, gloss('mark indicating conformity with requirements'), source('24').
:- pred post_market_monitoring_system/1, gloss('activities by providers to collect and review experience'), source('25').
:- pred market_surveillance_authority/1, gloss('national authority carrying out market surveillance'), source('26').
:- pred harmonised_standard/1, gloss('standard defined in EU legislation'), source('27').
:- pred common_specification/1, gloss('set of technical specifications to comply with requirements'), source('28').
:- pred training_data/1, gloss('data used for training an AI system'), source('29').
:- pred validation_data/1, gloss('data used for evaluating and tuning a trained AI system'), source('30').
:- pred validation_data_set/1, gloss('separate data set for validation'), source('31').
:- pred testing_data/1, gloss('data used for independent evaluation before market placement'), source('32').
:- pred input_data/1, gloss('data provided to an AI system to produce output'), source('33').
:- pred biometric_data/1, gloss('personal data from physical or behavioural characteristics'), source('34').
:- pred biometric_identification/1, gloss('automated recognition to establish identity by comparing biometric data'), source('35').
:- pred biometric_verification/1, gloss('one‑to‑one verification of identity using biometric data'), source('36').
:- pred special_categories_of_personal_data/1, gloss('categories of personal data defined in GDPR'), source('37').
:- pred sensitive_operational_data/1, gloss('operational data related to criminal investigations'), source('38').
:- pred emotion_recognition_system/1, gloss('AI system identifying emotions from biometric data'), source('39').
:- pred biometric_categorisation_system/1, gloss('AI system assigning persons to categories based on biometric data'), source('40').
:- pred remote_biometric_identification_system/1, gloss('AI system identifying persons without active involvement at a distance'), source('41').
:- pred real_time_remote_biometric_identification_system/1, gloss('remote biometric ID system with no significant delay'), source('42').
:- pred post_remote_biometric_identification_system/1, gloss('remote biometric ID system that is not real‑time'), source('43').
:- pred publicly_accessible_space/1, gloss('any place accessible to an undetermined number of persons'), source('44').
:- pred law_enforcement_authority/1, gloss('public authority for criminal investigation and prosecution'), source('45').
:- pred law_enforcement/1, gloss('activities carried out by law enforcement authorities'), source('46').
:- pred ai_office/1, gloss('Commission function for AI governance'), source('47').
:- pred national_competent_authority/1, gloss('notifying authority or market surveillance authority'), source('48').
:- pred serious_incident/1, gloss('incident leading to death, serious harm, or critical disruption'), source('49').
:- pred personal_data/1, gloss('personal data as defined in GDPR'), source('50').
:- pred non_personal_data/1, gloss('data other than personal data'), source('51').
:- pred profiling/1, gloss('profiling as defined in GDPR'), source('52').
:- pred real_world_testing_plan/1, gloss('document describing real‑world testing objectives and methodology'), source('53').
:- pred sandbox_plan/1, gloss('document describing sandbox objectives and conditions'), source('54').
:- pred ai_regulatory_sandbox/1, gloss('controlled framework for testing AI systems under supervision'), source('55').
:- pred ai_literacy/1, gloss('knowledge allowing informed deployment of AI systems'), source('56').
:- pred testing_in_real_world_conditions/1, gloss('temporary testing of an AI system in real‑world conditions'), source('57').
:- pred subject/1, gloss('natural person participating in real‑world testing'), source('58').
:- pred informed_consent/1, gloss('freely given specific consent for participation'), source('59').
:- pred deep_fake/1, gloss('AI‑generated content that falsely appears authentic'), source('60').
:- pred widespread_infringement/1, gloss('act contrary to Union law affecting multiple Member States'), source('61').
:- pred critical_infrastructure/1, gloss('critical infrastructure as defined in EU law'), source('62').
:- pred general_purpose_ai_model/1, gloss('AI model capable of a wide range of tasks'), source('63').
:- pred high_impact_capabilities/1, gloss('capabilities matching advanced general‑purpose AI models'), source('64').
:- pred systemic_risk/1, gloss('risk specific to high‑impact capabilities of general‑purpose AI models'), source('65').
:- pred general_purpose_ai_system/1, gloss('AI system based on a general‑purpose AI model'), source('66').
:- pred floating_point_operation/1, gloss('operation involving floating‑point numbers'), source('67').
:- pred downstream_provider/1, gloss('provider integrating an AI model into a system'), source('68').

% Additional predicates used in compositional definitions
:- pred remote/1, gloss('without active involvement'), source('41').
:- pred real_time/1, gloss('without significant delay'), source('42').
:- pred product_manufacturer/1, gloss('entity manufacturing a product'), source('8').
:- pred notified/1, gloss('entity that has been notified'), source('22').

% Compositional rules
remote_biometric_identification_system(S) :-
    ai_system(S),
    remote(S),
    biometric_identification(S).

real_time_remote_biometric_identification_system(S) :-
    remote_biometric_identification_system(S),
    real_time(S).

post_remote_biometric_identification_system(S) :-
    remote_biometric_identification_system(S),
    \+ real_time_remote_biometric_identification_system(S).

operator(O) :-
    provider(O).
operator(O) :-
    product_manufacturer(O).
operator(O) :-
    deployer(O).
operator(O) :-
    authorised_representative(O).
operator(O) :-
    importer(O).
operator(O) :-
    distributor(O).

notified_body(B) :-
    conformity_assessment_body(B),
    notified(B).

% Provenance for compositional rules
provenance(remote_biometric_identification_system/1, '41').
provenance(real_time_remote_biometric_identification_system/1, '42').
provenance(post_remote_biometric_identification_system/1, '43').
provenance(operator/1, '8').
provenance(notified_body/1, '22').
