% ============================================================
% FROZEN SIGNATURE -- the predicate vocabulary for v2.
%
% Generated by ONE LLM call over the definitions article, then frozen.
% Every Phase B rule-generation call receives this file verbatim, so all
% Phase B calls are mutually independent and order-free.
%
% source slice : art_3_definitions (68 items)
% slice sha256 : ff1109ad8737ad9a8abc40a3eff5be53fb268b8d348de73a57b6101339b6c014
% source unit  : celex:32024R1689/oj#art_3
% model        : gpt-oss:120b-cloud (temperature 0.0, seed 0)
% prompt sha   : 152ee51a2c386f8ce39638d82f3c61b91765ffa6ec99336d9e2149e783234942
% declarations : 65
%
% DO NOT EDIT BY HAND without re-running Phase B: rules generated against a
% different signature may reference predicates that no longer exist.
% ============================================================

% Entities
:- pred ai_system/1, gloss('machine‑based system with autonomy'), source('3.1').
:- pred provider/1, gloss('person or body that develops or places an AI system'), source('3.3').
:- pred deployer/1, gloss('person or body using an AI system under its authority'), source('3.4').
:- pred authorised_representative/1, gloss('person in the Union acting on behalf of a provider'), source('3.5').
:- pred importer/1, gloss('person in the Union placing an AI system on the market'), source('3.6').
:- pred distributor/1, gloss('person in the supply chain other than provider or importer'), source('3.7').
:- pred operator/1, gloss('provider, product manufacturer, deployer, authorised representative, importer or distributor'), source('3.8').
:- pred safety_component/1, gloss('component fulfilling a safety function'), source('3.14').
:- pred notifying_authority/1, gloss('national authority responsible for conformity procedures'), source('3.19').
:- pred conformity_assessment_body/1, gloss('body performing third‑party conformity assessment'), source('3.21').
:- pred notified_body/1, gloss('conformity assessment body notified under Union law'), source('3.22').
:- pred post_market_monitoring_system/1, gloss('system for monitoring AI systems after market placement'), source('3.25').
:- pred market_surveillance_authority/1, gloss('national authority carrying out market surveillance'), source('3.26').
:- pred harmonised_standard/1, gloss('standard defined in Union legislation'), source('3.27').
:- pred common_specification/1, gloss('set of technical specifications to meet requirements'), source('3.28').
:- pred emotion_recognition_system/1, gloss('AI system identifying emotions from biometric data'), source('3.39').
:- pred biometric_categorisation_system/1, gloss('AI system assigning persons to categories based on biometric data'), source('3.40').
:- pred remote_biometric_identification_system/1, gloss('AI system identifying persons at a distance without active involvement'), source('3.41').
:- pred real_time_remote_biometric_identification_system/1, gloss('remote biometric ID system operating with no significant delay'), source('3.42').
:- pred post_remote_biometric_identification_system/1, gloss('remote biometric ID system that is not real‑time'), source('3.43').
:- pred publicly_accessible_space/1, gloss('any place accessible to an undetermined number of persons'), source('3.44').
:- pred law_enforcement_authority/1, gloss('public authority competent for criminal matters'), source('3.45').
:- pred law_enforcement/1, gloss('activities carried out by law enforcement authorities'), source('3.46').
:- pred ai_office/1, gloss('Commission function for AI governance'), source('3.47').
:- pred national_competent_authority/1, gloss('notifying or market surveillance authority'), source('3.48').
:- pred serious_incident/1, gloss('incident leading to death, serious harm, or critical disruption'), source('3.49').
:- pred personal_data/1, gloss('information relating to an identified or identifiable natural person'), source('3.50').
:- pred non_personal_data/1, gloss('data that is not personal data'), source('3.51').
:- pred profiling/1, gloss('automated processing to evaluate personal aspects'), source('3.52').
:- pred real_world_testing_plan/1, gloss('document describing real‑world testing objectives and methods'), source('3.53').
:- pred sandbox_plan/1, gloss('document agreeing on sandbox objectives and conditions'), source('3.54').
:- pred ai_regulatory_sandbox/1, gloss('controlled framework for testing innovative AI systems'), source('3.55').
:- pred ai_literacy/1, gloss('knowledge enabling informed deployment of AI systems'), source('3.56').
:- pred testing_in_real_world_conditions/1, gloss('temporary testing of an AI system outside a lab'), source('3.57').
:- pred subject_for_real_world_testing/1, gloss('natural person participating in real‑world testing'), source('3.58').
:- pred informed_consent/1, gloss('voluntary expression to participate in testing'), source('3.59').
:- pred deep_fake/1, gloss('AI‑generated content that falsely appears authentic'), source('3.60').
:- pred widespread_infringement/1, gloss('act contrary to Union law affecting multiple Member States'), source('3.61').
:- pred critical_infrastructure/1, gloss('infrastructure defined in Union law'), source('3.62').
:- pred general_purpose_ai_model/1, gloss('AI model capable of a wide range of tasks'), source('3.63').
:- pred high_impact_capabilities/1, gloss('capabilities matching advanced general‑purpose AI models'), source('3.64').
:- pred systemic_risk/1, gloss('risk specific to high‑impact AI models affecting the Union market'), source('3.65').
:- pred general_purpose_ai_system/1, gloss('AI system based on a general‑purpose AI model'), source('3.66').
:- pred floating_point_operation/1, gloss('operation involving floating‑point numbers'), source('3.67').
:- pred downstream_provider/1, gloss('provider integrating an AI model into a system'), source('3.68').

% Properties
:- pred risk/1, gloss('combination of probability and severity of harm'), source('3.2').
:- pred operator/1, gloss('entity performing operator functions'), source('3.8').
:- pred remote/1, gloss('system operates without active involvement of the person'), source('3.41').
:- pred real_time/1, gloss('operation occurs without significant delay'), source('3.42').
:- pred reasonably_foreseeable_misuse/1, gloss('use not in accordance with intended purpose but foreseeable'), source('3.13').
:- pred substantial_modification/1, gloss('change after market placement affecting compliance'), source('3.23').
:- pred ce_marking/1, gloss('mark indicating conformity with requirements'), source('3.24').
:- pred biometric_identification/1, gloss('automated recognition to establish identity'), source('3.35').
:- pred biometric_verification/1, gloss('one‑to‑one verification of identity'), source('3.36').
:- pred special_categories_of_personal_data/1, gloss('sensitive categories defined in Union law'), source('3.37').
:- pred sensitive_operational_data/1, gloss('operational data related to criminal investigations'), source('3.38').

% Relations
:- pred placing_on_market/2, gloss('first making available of an AI system on the Union market'), source('3.9').
:- pred making_available_on_market/2, gloss('supply of an AI system for distribution or use'), source('3.10').
:- pred putting_into_service/2, gloss('supply of an AI system for first use by the deployer'), source('3.11').
:- pred intended_purpose/2, gloss('use for which an AI system is intended by the provider'), source('3.12').
:- pred instructions_for_use/2, gloss('information provided by the provider to the deployer'), source('3.15').
:- pred recall_of_ai_system/1, gloss('measure to return or disable an AI system'), source('3.16').
:- pred withdrawal_of_ai_system/1, gloss('measure to prevent AI system being made available'), source('3.17').
:- pred performance_of_ai_system/1, gloss('ability of an AI system to achieve its intended purpose'), source('3.18').
:- pred conformity_assessment/1, gloss('process demonstrating fulfillment of high‑risk requirements'), source('3.20').

% Decomposition rules
real_time_remote_biometric_identification_system(S) :-
    remote_biometric_identification_system(S),
    real_time(S).

post_remote_biometric_identification_system(S) :-
    remote_biometric_identification_system(S),
    \+ real_time_remote_biometric_identification_system(S).

% Provenance
provenance(real_time_remote_biometric_identification_system/1, '3.42').
provenance(post_remote_biometric_identification_system/1, '3.43').
