% ============================================================
% FROZEN SIGNATURE -- the predicate vocabulary for v2.
%
% Generated by ONE LLM call over the definitions article, then frozen.
% Every Phase B rule-generation call receives this file verbatim, so all
% Phase B calls are mutually independent and order-free.
%
% source slice : art_3_definitions (68 items)
% slice sha256 : ff1109ad8737ad9a8abc40a3eff5be53fb268b8d348de73a57b6101339b6c014
% source unit  : celex:32024R1689/oj#art_3
% model        : gpt-oss:120b-cloud (temperature 0.0, seed 0)
% prompt sha   : 152ee51a2c386f8ce39638d82f3c61b91765ffa6ec99336d9e2149e783234942
% declarations : 71
%
% DO NOT EDIT BY HAND without re-running Phase B: rules generated against a
% different signature may reference predicates that no longer exist.
% ============================================================

%--- Primitive predicates for each defined term (Article 3) ---
:- pred ai_system/1, gloss('machine‑based system with autonomy and adaptiveness'), source('3.1').
:- pred risk/1, gloss('combination of probability of harm and its severity'), source('3.2').
:- pred provider/1, gloss('entity that develops or places an AI system on the market'), source('3.3').
:- pred deployer/1, gloss('entity using an AI system under its authority'), source('3.4').
:- pred authorised_representative/1, gloss('person in the Union authorised by a provider to act on its behalf'), source('3.5').
:- pred importer/1, gloss('entity placing on the market an AI system bearing a third‑country name'), source('3.6').
:- pred distributor/1, gloss('natural or legal person in the supply chain other than provider or importer'), source('3.7').
:- pred operator/1, gloss('provider, product manufacturer, deployer, authorised representative, importer or distributor'), source('3.8').
:- pred places_on_market/2, gloss('first making available of an AI system on the Union market'), source('3.9').
:- pred makes_available_on_market/2, gloss('supply of an AI system for distribution or use on the Union market'), source('3.10').
:- pred puts_into_service/2, gloss('supply of an AI system for first use by the deployer or for own use'), source('3.11').
:- pred intended_purpose/2, gloss('use for which an AI system is intended by the provider'), source('3.12').
:- pred reasonably_foreseeable_misuse/1, gloss('use of an AI system contrary to its intended purpose but reasonably foreseeable'), source('3.13').
:- pred safety_component/1, gloss('component fulfilling a safety function for a product or AI system'), source('3.14').
:- pred instructions_for_use/1, gloss('information provided by the provider to inform the deployer'), source('3.15').
:- pred recall/1, gloss('measure aiming to return or disable an AI system made available to deployers'), source('3.16').
:- pred withdrawal/1, gloss('measure aiming to prevent an AI system from being made available on the market'), source('3.17').
:- pred performance/1, gloss('ability of an AI system to achieve its intended purpose'), source('3.18').
:- pred notifying_authority/1, gloss('national authority responsible for conformity assessment procedures'), source('3.19').
:- pred conformity_assessment/1, gloss('process demonstrating fulfilment of high‑risk AI system requirements'), source('3.20').
:- pred conformity_assessment_body/1, gloss('body performing third‑party conformity assessment activities'), source('3.21').
:- pred notified_body/1, gloss('conformity assessment body notified in accordance with Union legislation'), source('3.22').
:- pred substantial_modification/1, gloss('change to an AI system after market placement affecting compliance'), source('3.23').
:- pred ce_marking/1, gloss('mark indicating conformity of an AI system with Union requirements'), source('3.24').
:- pred post_market_monitoring_system/1, gloss('activities by providers to collect and review experience from AI systems in use'), source('3.25').
:- pred market_surveillance_authority/1, gloss('national authority carrying out market surveillance activities'), source('3.26').
:- pred harmonised_standard/1, gloss('standard defined in Union legislation'), source('3.27').
:- pred common_specification/1, gloss('set of technical specifications to comply with certain requirements'), source('3.28').
:- pred training_data/1, gloss('data used for training an AI system'), source('3.29').
:- pred validation_data/1, gloss('data used to evaluate and tune a trained AI system'), source('3.30').
:- pred validation_data_set/1, gloss('separate data set or part of the training data set'), source('3.31').
:- pred testing_data/1, gloss('data used for independent evaluation before market placement'), source('3.32').
:- pred input_data/1, gloss('data provided to or acquired by an AI system to produce an output'), source('3.33').
:- pred biometric_data/1, gloss('personal data resulting from processing of physical/physiological/behavioural characteristics'), source('3.34').
:- pred biometric_identification/1, gloss('automated recognition of human features to establish identity'), source('3.35').
:- pred biometric_verification/1, gloss('automated one‑to‑one verification of identity using biometric data'), source('3.36').
:- pred special_categories_of_personal_data/1, gloss('categories of personal data listed in Union law'), source('3.37').
:- pred sensitive_operational_data/1, gloss('operational data related to criminal investigations whose disclosure could jeopardise proceedings'), source('3.38').
:- pred emotion_recognition_system/1, gloss('AI system identifying or inferring emotions from biometric data'), source('3.39').
:- pred biometric_categorisation_system/1, gloss('AI system assigning persons to categories based on biometric data'), source('3.40').
:- pred remote_biometric_identification_system/1, gloss('AI system identifying persons at a distance without active involvement'), source('3.41').
:- pred real_time_remote_biometric_identification_system/1, gloss('remote biometric identification where capture, comparison and identification occur without significant delay'), source('3.42').
:- pred post_remote_biometric_identification_system/1, gloss('remote biometric identification system that is not real‑time'), source('3.43').
:- pred publicly_accessible_space/1, gloss('any place accessible to an undetermined number of persons'), source('3.44').
:- pred law_enforcement_authority/1, gloss('public authority competent for criminal investigations or other body entrusted with such powers'), source('3.45').
:- pred law_enforcement/1, gloss('activities carried out by law enforcement authorities or on their behalf'), source('3.46').
:- pred ai_office/1, gloss('Commission function contributing to AI system implementation, monitoring and supervision'), source('3.47').
:- pred national_competent_authority/1, gloss('notifying authority or market surveillance authority'), source('3.48').
:- pred serious_incident/1, gloss('incident or malfunction of an AI system leading to death, critical infrastructure disruption, rights infringement or serious harm'), source('3.49').
:- pred personal_data/1, gloss('personal data as defined in Union law'), source('3.50').
:- pred non_personal_data/1, gloss('data other than personal data'), source('3.51').
:- pred profiling/1, gloss('profiling as defined in Union law'), source('3.52').
:- pred real_world_testing_plan/1, gloss('document describing objectives and methodology for real‑world testing'), source('3.53').
:- pred sandbox_plan/1, gloss('document describing objectives and conditions for a sandbox'), source('3.54').
:- pred ai_regulatory_sandbox/1, gloss('controlled framework allowing providers to develop and test AI systems under supervision'), source('3.55').
:- pred ai_literacy/1, gloss('skills and knowledge enabling informed deployment of AI systems'), source('3.56').
:- pred testing_in_real_world_conditions/1, gloss('temporary testing of an AI system in real‑world conditions outside a lab'), source('3.57').
:- pred subject/1, gloss('natural person participating in real‑world testing'), source('3.58').
:- pred informed_consent/1, gloss('freely given, specific and unambiguous expression of willingness to participate'), source('3.59').
:- pred deep_fake/1, gloss('AI‑generated or manipulated content that falsely appears authentic'), source('3.60').
:- pred widespread_infringement/1, gloss('act or omission contrary to Union law harming collective interests in multiple Member States'), source('3.61').
:- pred critical_infrastructure/1, gloss('critical infrastructure as defined in Union legislation'), source('3.62').
:- pred general_purpose_ai_model/1, gloss('AI model capable of a wide range of tasks and integrable into downstream systems'), source('3.63').
:- pred high_impact_capabilities/1, gloss('capabilities matching or exceeding those of the most advanced general‑purpose AI models'), source('3.64').
:- pred systemic_risk/1, gloss('risk specific to high‑impact capabilities of general‑purpose AI models with large‑scale effects'), source('3.65').
:- pred general_purpose_ai_system/1, gloss('AI system based on a general‑purpose AI model serving various purposes'), source('3.66').
:- pred floating_point_operation/1, gloss('mathematical operation involving floating‑point numbers'), source('3.67').
:- pred downstream_provider/1, gloss('provider of an AI system that integrates an AI model'), source('3.68').

%--- Additional primitive predicates needed for decomposition ---
:- pred remote/1, gloss('operating without active involvement of the person'), source('derived').
:- pred real_time/1, gloss('occurring without significant delay'), source('derived').
:- pred product_manufacturer/1, gloss('entity that manufactures a product'), source('derived').

%--- Decomposition rules ---
operator(X) :- provider(X).
operator(X) :- product_manufacturer(X).
operator(X) :- deployer(X).
operator(X) :- authorised_representative(X).
operator(X) :- importer(X).
operator(X) :- distributor(X).

remote_biometric_identification_system(S) :- ai_system(S), remote(S), biometric_identification(S).

real_time_remote_biometric_identification_system(S) :- remote_biometric_identification_system(S), real_time(S).

post_remote_biometric_identification_system(S) :- remote_biometric_identification_system(S), \+ real_time_remote_biometric_identification_system(S).

%--- Provenance for decomposition rules ---
provenance(operator/1, '3.8').
provenance(remote_biometric_identification_system/1, '3.41').
provenance(real_time_remote_biometric_identification_system/1, '3.42').
provenance(post_remote_biometric_identification_system/1, '3.43').
