"""Phase A -- build the predicate vocabulary, then freeze it.

The signature is the namespace every Phase B call writes into. It is produced by ONE
LLM call over Article 3's definitions, written to out_v2/signature.pl, and content-
hashed. Phase B refuses to run against a signature whose hash is not recorded in the
manifest, so a signature can never change silently underneath a set of rules.

Freezing is the point. See prompt_v2.py for why.
"""
from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import re
import sys
from pathlib import Path

import httpx

sys.path.insert(0, str(Path(__file__).parent))
from llm import Client, LLMConfig, append_log  # noqa: E402
from prompt_v2 import build_signature_messages  # noqa: E402
from slice import SPECS, slice_one  # noqa: E402

PRED_DECL_RE = re.compile(r":-\s*pred\s+([a-z_][A-Za-z0-9_]*)\s*/\s*(\d+)")
SOURCE_RE = re.compile(r"source\(\s*'([^']*)'\s*\)")


def parse_declarations(text: str) -> list[tuple[str, int]]:
    """The (name, arity) pairs a signature declares, in order of appearance."""
    return [(n, int(a)) for n, a in PRED_DECL_RE.findall(text)]


def signature_sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def cited_items(text: str) -> set[str]:
    """The item labels a signature's source(...) annotations point at.

    The model is inconsistent about the format -- '29' in one run, '3.29' in another,
    and a full unit id in Phase B output. Take the last dot-separated component, which
    is the item label in every form seen.
    """
    return {raw.strip().split(".")[-1].strip() for raw in SOURCE_RE.findall(text)}


def coverage_report(text: str, items: tuple[str, ...]) -> dict:
    """Which of the slice's own enumerated items the signature actually declares.

    Deliberately NOT a hardcoded count: `items` comes from the slice spec's item_re,
    so a different act or a different slice is checked against its own enumeration.
    An empty `items` (a slice with no enumeration) makes this a no-op.
    """
    expected = list(dict.fromkeys(items))          # de-duplicated, order preserved
    cited = cited_items(text)
    missing = [i for i in expected if i not in cited]
    return {
        "expected": len(expected),
        "cited": len(expected) - len(missing),
        "missing": missing,
        "ratio": round((len(expected) - len(missing)) / len(expected), 3) if expected else None,
    }


def print_coverage(cov: dict, slice_name: str) -> None:
    """One terminal block so a gap is visible without reading signature.pl."""
    if cov["expected"] == 0:
        return
    print(f"\n== coverage check: {slice_name} ==")
    print(f"  items in slice        {cov['expected']}")
    print(f"  items with a source   {cov['cited']}  ({cov['ratio']:.0%})")
    if not cov["missing"]:
        print("  OK -- every item in the slice is accounted for")
        return
    print(f"  NOT DECLARED          {len(cov['missing'])}: {', '.join(cov['missing'])}")
    print("  These items produced no declaration, so they are absent from the frozen")
    print("  vocabulary. Phase B will invent its own names for them, inconsistently")
    print("  across calls. Resample Phase A with --force if that matters.")


async def build(args: argparse.Namespace) -> int:
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    sig_path = out_dir / "signature.pl"

    sl = slice_one(Path(args.units), SPECS[args.slice])

    if sig_path.exists() and not args.force:
        text = sig_path.read_text(encoding="utf-8")
        decls = parse_declarations(text)
        print(f"signature.pl already exists ({len(decls)} predicates, "
              f"sha {signature_sha(text)[:12]}). Use --force to rebuild.")
        print_coverage(coverage_report(text, sl.items), sl.name)
        return 0

    print(f"input slice : {sl.name}  {sl.n_items} items  {len(sl.text):,} chars  "
          f"sha {sl.sha256[:12]}")

    cfg = LLMConfig(model=args.model, host=args.host, concurrency=1)
    client = Client(cfg, out_dir / "cache")
    messages = build_signature_messages(sl.text)

    async with httpx.AsyncClient() as http:
        text, rec = await client.call(http, messages, label=f"signature:{sl.name}")
    append_log(out_dir / "run.jsonl", rec)

    if not rec.ok:
        print(f"FAILED: {rec.error}", file=sys.stderr)
        return 1

    decls = parse_declarations(text)
    header = (
        "% ============================================================\n"
        "% FROZEN SIGNATURE -- the predicate vocabulary for v2.\n"
        "%\n"
        "% Generated by ONE LLM call over the definitions article, then frozen.\n"
        "% Every Phase B rule-generation call receives this file verbatim, so all\n"
        "% Phase B calls are mutually independent and order-free.\n"
        "%\n"
        f"% source slice : {sl.name} ({sl.n_items} items)\n"
        f"% slice sha256 : {sl.sha256}\n"
        f"% source unit  : {sl.unit_id}\n"
        f"% model        : {cfg.model} (temperature {cfg.temperature}, seed {cfg.seed})\n"
        f"% prompt sha   : {rec.prompt_sha}\n"
        f"% declarations : {len(decls)}\n"
        "%\n"
        "% DO NOT EDIT BY HAND without re-running Phase B: rules generated against a\n"
        "% different signature may reference predicates that no longer exist.\n"
        "% ============================================================\n\n"
    )
    sig_path.write_text(header + text + "\n", encoding="utf-8")

    full = sig_path.read_text(encoding="utf-8")
    meta = {
        "slice": sl.name,
        "slice_sha256": sl.sha256,
        "signature_sha256": signature_sha(full),
        "model": cfg.model,
        "temperature": cfg.temperature,
        "seed": cfg.seed,
        "prompt_sha": rec.prompt_sha,
        "cached": rec.cached,
        "n_declarations": len(decls),
        "declarations": [f"{n}/{a}" for n, a in decls],
        "item_coverage": coverage_report(full, sl.items),
    }
    (out_dir / "signature.meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

    dupes = [d for d in {n for n, _ in decls}
             if len({a for n, a in decls if n == d}) > 1]
    print(f"\nwrote {sig_path}")
    print(f"  declarations : {len(decls)}")
    print(f"  distinct     : {len({n for n, _ in decls})}")
    print(f"  sha256       : {meta['signature_sha256'][:12]}")
    print(f"  cached       : {rec.cached}")
    if dupes:
        print(f"  WARNING: predicates declared at two arities: {dupes}")
    print_coverage(meta["item_coverage"], sl.name)
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Phase A -- build and freeze the signature.")
    p.add_argument("--units", default="20260922T172249_32024R1689_3f672e3e/units")
    p.add_argument("--out", default="out_v2")
    p.add_argument("--slice", default="art_3_definitions", choices=sorted(SPECS))
    p.add_argument("--model", default=LLMConfig.model)
    p.add_argument("--host", default=LLMConfig.host)
    p.add_argument("--force", action="store_true", help="rebuild even if signature.pl exists")
    return p


if __name__ == "__main__":
    sys.exit(asyncio.run(build(build_parser().parse_args())))
