% ============================================================
% FROZEN SIGNATURE -- the predicate vocabulary for v2.
%
% Generated by ONE LLM call over the definitions article, then frozen.
% Every Phase B rule-generation call receives this file verbatim, so all
% Phase B calls are mutually independent and order-free.
%
% source slice : art_3_definitions (68 items)
% slice sha256 : ff1109ad8737ad9a8abc40a3eff5be53fb268b8d348de73a57b6101339b6c014
% source unit  : celex:32024R1689/oj#art_3
% model        : gpt-oss:120b-cloud (temperature 0.0, seed 0)
% prompt sha   : 152ee51a2c386f8ce39638d82f3c61b91765ffa6ec99336d9e2149e783234942
% declarations : 70
%
% DO NOT EDIT BY HAND without re-running Phase B: rules generated against a
% different signature may reference predicates that no longer exist.
% ============================================================

:- pred ai_system/1, gloss('machine-based system with autonomy and adaptiveness'), source('1').
:- pred risk/1, gloss('combination of probability and severity of harm'), source('2').
:- pred provider/1, gloss('natural or legal person that develops or places an AI system on the market'), source('3').
:- pred deployer/1, gloss('natural or legal person using an AI system under its authority'), source('4').
:- pred authorised_representative/1, gloss('person in the Union mandated by a provider to act on its behalf'), source('5').
:- pred importer/1, gloss('person in the Union placing on the market an AI system bearing a third‑country name'), source('6').
:- pred distributor/1, gloss('person in the supply chain other than provider or importer making an AI system available'), source('7').
:- pred product_manufacturer/1, gloss('entity that manufactures a product incorporating an AI system'), source('8').
:- pred operator/1, gloss('entity that is a provider, product manufacturer, deployer, authorised representative, importer or distributor'), source('8').
:- pred places_on_market/2, gloss('first making available of an AI system or model on the Union market'), source('9').
:- pred making_available_on_market/2, gloss('supply of an AI system or model for distribution or use on the Union market'), source('10').
:- pred putting_into_service/2, gloss('supply of an AI system for first use directly to the deployer or for own use'), source('11').
:- pred intended_purpose/2, gloss('use for which an AI system is intended by the provider'), source('12').
:- pred reasonably_foreseeable_misuse/1, gloss('use of an AI system contrary to its intended purpose but foreseeable'), source('13').
:- pred safety_component/1, gloss('component of a product or AI system that fulfills a safety function'), source('14').
:- pred instructions_for_use/1, gloss('information provided by the provider to inform the deployer of intended purpose and proper use'), source('15').
:- pred recall_of_ai_system/1, gloss('measure aiming to return to the provider or disable an AI system'), source('16').
:- pred withdrawal_of_ai_system/1, gloss('measure aiming to prevent an AI system from being made available on the market'), source('17').
:- pred performance_of_ai_system/1, gloss('ability of an AI system to achieve its intended purpose'), source('18').
:- pred notifying_authority/1, gloss('national authority responsible for conformity assessment procedures'), source('19').
:- pred conformity_assessment/1, gloss('process demonstrating fulfillment of high‑risk AI system requirements'), source('20').
:- pred conformity_assessment_body/1, gloss('body that performs third‑party conformity assessment activities'), source('21').
:- pred notified_body/1, gloss('conformity assessment body notified in accordance with Union legislation'), source('22').
:- pred substantial_modification/1, gloss('change to an AI system after market placement affecting compliance'), source('23').
:- pred ce_marking/1, gloss('mark indicating conformity of an AI system with Union requirements'), source('24').
:- pred post_market_monitoring_system/1, gloss('activities by providers to collect and review experience from AI system use'), source('25').
:- pred market_surveillance_authority/1, gloss('national authority carrying out market surveillance activities'), source('26').
:- pred harmonised_standard/1, gloss('standard defined in Union legislation'), source('27').
:- pred common_specification/1, gloss('set of technical specifications providing means to comply with requirements'), source('28').
:- pred training_data/1, gloss('data used for training an AI system'), source('29').
:- pred validation_data/1, gloss('data used to evaluate and tune a trained AI system'), source('30').
:- pred validation_data_set/1, gloss('separate data set or part of the training data set'), source('31').
:- pred testing_data/1, gloss('data used for independent evaluation of an AI system before market placement'), source('32').
:- pred input_data/1, gloss('data provided to or acquired by an AI system to produce an output'), source('33').
:- pred biometric_data/1, gloss('personal data resulting from processing of physical, physiological or behavioural characteristics'), source('34').
:- pred biometric_identification/1, gloss('automated recognition of a natural person by comparing biometric data to a database'), source('35').
:- pred biometric_verification/1, gloss('automated one‑to‑one verification of a natural person’s identity'), source('36').
:- pred special_categories_of_personal_data/1, gloss('categories of personal data listed in Union law'), source('37').
:- pred sensitive_operational_data/1, gloss('operational data related to criminal investigations whose disclosure could jeopardise proceedings'), source('38').
:- pred emotion_recognition_system/1, gloss('AI system identifying or inferring emotions or intentions from biometric data'), source('39').
:- pred biometric_categorisation_system/1, gloss('AI system assigning persons to categories based on biometric data'), source('40').
:- pred remote_biometric_identification_system/1, gloss('AI system identifying persons without active involvement, typically at a distance'), source('41').
:- pred real_time_remote_biometric_identification_system/1, gloss('remote biometric identification where capture, comparison and identification occur without significant delay'), source('42').
:- pred post_remote_biometric_identification_system/1, gloss('remote biometric identification system that is not real‑time'), source('43').
:- pred publicly_accessible_space/1, gloss('any physical place accessible to an undetermined number of persons'), source('44').
:- pred law_enforcement_authority/1, gloss('public authority competent for criminal investigation or other body entrusted with such powers'), source('45').
:- pred law_enforcement/1, gloss('activities carried out by law enforcement authorities or on their behalf'), source('46').
:- pred ai_office/1, gloss('Commission function contributing to AI system implementation, monitoring and supervision'), source('47').
:- pred national_competent_authority/1, gloss('notifying authority or market surveillance authority'), source('48').
:- pred serious_incident/1, gloss('incident or malfunctioning of an AI system leading to death, serious harm, critical infrastructure disruption, or rights infringement'), source('49').
:- pred personal_data/1, gloss('personal data as defined in Union law'), source('50').
:- pred non_personal_data/1, gloss('data other than personal data'), source('51').
:- pred profiling/1, gloss('profiling as defined in Union law'), source('52').
:- pred real_world_testing_plan/1, gloss('document describing objectives and methodology for testing in real‑world conditions'), source('53').
:- pred sandbox_plan/1, gloss('document agreed between provider and competent authority describing sandbox activities'), source('54').
:- pred ai_regulatory_sandbox/1, gloss('controlled framework allowing providers to develop and test innovative AI systems under supervision'), source('55').
:- pred ai_literacy/1, gloss('skills and knowledge enabling informed deployment of AI systems'), source('56').
:- pred testing_in_real_world_conditions/1, gloss('temporary testing of an AI system in real‑world conditions outside a laboratory'), source('57').
:- pred subject/1, gloss('natural person participating in real‑world testing'), source('58').
:- pred informed_consent/1, gloss('freely given, specific and unambiguous expression of willingness to participate in testing'), source('59').
:- pred deep_fake/1, gloss('AI‑generated or manipulated content that falsely appears authentic'), source('60').
:- pred widespread_infringement/1, gloss('act or omission contrary to Union law affecting individuals in multiple Member States'), source('61').
:- pred critical_infrastructure/1, gloss('critical infrastructure as defined in Union law'), source('62').
:- pred general_purpose_ai_model/1, gloss('AI model displaying significant generality and capable of many tasks'), source('63').
:- pred high_impact_capabilities/1, gloss('capabilities matching or exceeding those of the most advanced general‑purpose AI models'), source('64').
:- pred systemic_risk/1, gloss('risk specific to high‑impact capabilities of general‑purpose AI models affecting the Union market'), source('65').
:- pred general_purpose_ai_system/1, gloss('AI system based on a general‑purpose AI model serving a variety of purposes'), source('66').
:- pred floating_point_operation/1, gloss('mathematical operation involving floating‑point numbers'), source('67').
:- pred downstream_provider/1, gloss('provider of an AI system that integrates an AI model'), source('68').
:- pred real_time/1, gloss('property indicating operation without significant delay'), source('42').

% Decomposition rules
operator(O) :-
    provider(O).
operator(O) :-
    product_manufacturer(O).
operator(O) :-
    deployer(O).
operator(O) :-
    authorised_representative(O).
operator(O) :-
    importer(O).
operator(O) :-
    distributor(O).

real_time_remote_biometric_identification_system(S) :-
    remote_biometric_identification_system(S),
    real_time(S).

post_remote_biometric_identification_system(S) :-
    remote_biometric_identification_system(S),
    \+ real_time(S).

% Provenance for decomposition rules
provenance(operator/1, '8').
provenance(real_time_remote_biometric_identification_system/1, '42').
provenance(post_remote_biometric_identification_system/1, '43').
